// Generated by CoffeeScript 1.12.7
(function() {
  var photoDiv, running, showPhotos, socket;

  socket = io.connect('http://localhost:8000');

  socket.emit('dimensions', {
    width: screen.width,
    height: screen.height
  });

  running = false;

  photoDiv = document.getElementById('photo');

  showPhotos = function(photos) {
    var img;
    if (photos.length) {
      console.log('SHOWING PHOTO');
      img = photos[0];
      photoDiv.style.display = 'block';
      photoDiv.innerHTML = "<img src=\"" + img + "\"/>";
      return setTimeout(function() {
        return showPhotos(photos.slice(1));
      }, 5000);
    } else {
      return photoDiv.style.display = 'none';
    }
  };

  window.onkeypress = function(evt) {
    if (running) {
      return;
    }
    running = true;
    return socket.emit('photo');
  };

  socket.on('done', function(response) {
    running = false;
    return showPhotos(response);
  });

  socket.on('fail', function() {
    return running = false;
  });

  navigator.mediaDevices.getUserMedia({
    video: true,
    audio: false
  }).then(function(stream) {
    var video;
    video = document.getElementsByTagName('video')[0];
    return video.srcObject = stream;
  });

}).call(this);
